tasks:
  - init: |
      docker-compose -f docker/docker-compose.yml pull
  - command: |
      ./kicker start

ports:
  - name: web3
    port: 8024
    onOpen: ignore
    visibility: public

  - port: 5432-8120
    onOpen: ignore
  - port: 28119-28120
    onOpen: ignore

