version: '3.8'

services:
  # Use the manual built executables of Polyjuice
  #
  # 1. First you have to build Polyjuice manually and copy the executables in
  # `build` dir to `docker/manual-artifacts/polyjuice`:
  #
  #   ```
  #   MANUAL_BUILD_POLYJUICE="true" \
  #   POLYJUICE_GIT_URL=https://github.com/keroro520/godwoken-polyjuice \
  #   POLYJUICE_GIT_CHECKOUT=6e4390df3d95484caaab5f37728cff1771b55c4e \
  #   ./kicker init
  #   ```
  #
  # 2. Then start docker-compose service:
  #
  #   ```
  #   MANUAL_BUILD_POLYJUICE="true" \
  #   POLYJUICE_GIT_URL=https://github.com/keroro520/godwoken-polyjuice \
  #   POLYJUICE_GIT_CHECKOUT=6e4390df3d95484caaab5f37728cff1771b55c4e \
  #   ./kicker start
  #   ```
  godwoken:
    volumes:
      - ./manual-artifacts/polyjuice:/scripts/godwoken-polyjuice
  godwoken-readonly:
    volumes:
      - ./manual-artifacts/polyjuice:/scripts/godwoken-polyjuice
