version: "3.8"

services:
  # Use the manual built executables of Scripts
  #
  # 1. First you have to build Scripts manually and copy the executables in
  # `build` dir to `docker/manual-artifacts/scripts`:
  #
  #   ```
  #   MANUAL_BUILD_SCRIPTS="true" \
  #   SCRIPTS_GIT_URL=https://github.com/keroro520/godwoken-scripts \
  #   SCRIPTS_GIT_CHECKOUT=6e4390df3d95484caaab5f37728cff1771b55c4e \
  #   ./kicker init
  #   ```
  #
  # 2. Then start docker-compose service:
  #
  #   ```
  #   MANUAL_BUILD_SCRIPTS="true" \
  #   SCRIPTS_GIT_URL=https://github.com/keroro520/godwoken-scripts \
  #   SCRIPTS_GIT_CHECKOUT=6e4390df3d95484caaab5f37728cff1771b55c4e \
  #   ./kicker start
  #   ```
  godwoken:
    volumes:
      - ./manual-artifacts/scripts:/scripts/godwoken-scripts
  godwoken-readonly:
    volumes:
      - ./manual-artifacts/scripts:/scripts/godwoken-scripts
